Update testreport from checkpoint69j

diff --git a/testreport b/testreport
--- a/testreport
+++ b/testreport
@@ -8,8 +8,9 @@ usage()
     echo "where possible OPTIONS are:"
     echo "  (-help|-h)               print usage"
     echo " ---- type of test : ----"
-    echo "  (-tlm)                   perform a Tangent Linear run"
-    echo "  (-adm|-ad)               perform an adjoint run"
+    echo "  (-tlm)                   perform a Tangent-Linear run (defaut: using TAF)"
+    echo "  (-adm|-ad)               perform an Adjoint run (default: using TAF)"
+    echo "  (-tap)                   use Tapenade for Adjoint or Tangent-Linear run"
     echo "  (-oad)                   perform an OpenAD adjoint run"
     echo "  (-oadsingularity|-oadsngl) STRING"
     echo "                           path to singularity container with OpenAD"
@@ -49,6 +50,7 @@ usage()
     echo " ---- output options : ----"
     echo "  (-match) NUMBER          Matching Criteria (number of digits)"
     echo "                             (DEF=\"$MATCH_CRIT\")"
+    echo "  (-pass)                  return non-zero exit code if any exp do not pass"
     echo "  (-odir) STRING           used to build output directory name"
     echo "                             (DEF=\"hostname\")"
     echo "  (-addr|-a) STRING        list of email recipients"
@@ -567,13 +569,13 @@ testoutput_run()
 	listChk=$DEF_CHECK_LIST
 	#  load experiment-specific list from file "tr_checklist" (if it exist)
 	if test -r $1/$2/tr_checklist ; then listChk=`cat $1/$2/tr_checklist` ; fi
-	if test $KIND = 1 ; then kd='g_';
+	if test $KIND = 1 -o $KIND = 4 ; then kd='g_';
 	  #  TLM use same input_ad/tr_checklist --> convert
 	  listChk=`echo $listChk | sed 's/^adm/tlm/' | sed 's/ adm/ tlm/g'`
 	  if test -r $1/$2/tr_checklist.tlm ; then listChk=`cat $1/$2/tr_checklist.tlm` ; fi
-	elif test $KIND = 2 ; then kd='ad';
+	elif test $KIND = 2 -o $KIND = 5 ; then kd='ad';
 	  if test -r $1/$2/tr_checklist.adm ; then listChk=`cat $1/$2/tr_checklist.adm` ; fi
-	elif test $KIND = 4 ; then kd='ad';
+	elif test $KIND = 6 ; then kd='ad';
         else kd=''; fi
 	if [ $debug -gt 0 ]; then echo "testoutput_run: listChk='$listChk'" 1>&2 ; fi
 	# remove 1rst var and expand the list: + => min max mean s.d
@@ -923,8 +925,10 @@ genmakemodel()
 	    if test "x$MKDEPEND" != x ; then
 		command="$command -makedepend=$MKDEPEND"
 	    fi
-	    if test $KIND = 4 ; then
+	    if test $KIND = 6 ; then
 		command="$command -oad -mods=../$code_dir"
+	    elif [ $KIND -ge 3 ] ; then
+		command="$command -tap -mods=../$code_dir"
 	    else
 		command="$command -mods=../$code_dir"
 	    fi
@@ -1132,29 +1136,32 @@ makemodel()
 	fi
 	echo " TAF reports $nerr Errors and $nwar Recomputation Warnings" \
 				>> $CDIR"/summary.txt"
-	if test -f ad_taf_output.f ; then
-	    adfile=ad_taf_output.f
-	elif test -f ad_taf_output.for ; then
-	    adfile=ad_taf_output.for
+	#- report number of calls for some key S/R, i.e.,
+	#   load_fields_driver, do_oceanic_phys, and seaice_model
+	#  Multiple calls indicate hidden but expensive recomputations
+	FS='f'
+	if test -f genmake_state ; then eval `grep '^FS=' genmake_state` ; fi
+	if test "x$NOCATAD" = xt ; then
+	    adfiles="*_ad.$FS"
 	else
-	    echo "WARNING: neither ad_output_ad.f nor ad_output_ad.for found" \
-				>> $CDIR"/summary.txt"
-	    adfile=missing ; nlfd=0 ; ndop=0 ; nsm=0
+	    adfiles=ad_taf_output.$FS
 	fi
-	if test $adfile != missing ; then
-	    # count number of times load_fields_driver and do_oceanic_phys are called
-	    nlfd=`grep "call load_fields_driver(" ${adfile} | wc -l`
-	    nlfdmd=`grep "call load_fields_drivermd(" ${adfile} | wc -l`
-	    if (( $nlfdmd == 0 )) ; then
-		# if there is no load_fields_driver, we can substract one assuming
-		# that load_fields_driver is called once from forward_stepmd
-		nlfd=$((nlfd-1))
-	    fi
-	    ndop=`grep "call do_oceanic_phys("    ${adfile} | wc -l`
-	    nsm=`grep "call seaice_model(" ${adfile} | wc -l`
+	nbf=`ls $adfiles 2> /dev/null | wc -l`
+	if [ $nbf -eq 0 ] ; then
+	    echo "WARNING: no adfiles '$adfiles' found" >> $CDIR"/summary.txt"
+	    nlfd=0 ; ndop=0 ; nsm=0
+	else
+	    nlfd=`grep "call load_fields_driver(" ${adfiles} | wc -l`
+	    nlfdmd=`grep "call load_fields_drivermd(" ${adfiles} | wc -l`
+	    nlfd=$((nlfd+nlfdmd-1))
+	    ndop=`grep "call do_oceanic_phys(" ${adfiles} | wc -l`
+	    nsm=`grep "call seaice_model(" ${adfiles} | wc -l`
 	fi
 	echo " load_fields_driver, do_oceanic_phys, seaice_model are called " \
 	     "( $nlfd , $ndop , $nsm ) time(s)" >> $CDIR"/summary.txt"
+    fi
+    if test -f make.tr_log && test $KIND = 4 -o $KIND = 5 ; then
+	grep '^Tapenade ' make.tr_log | tail -n 1 >> $CDIR"/summary.txt"
     fi
     if test $mk_fail != 0 ; then return $mk_fail ; fi
     )
@@ -1376,7 +1383,7 @@ runmodel()
 	    #echo '' ; echo "  COMMAND='$COMMAND'"
 	    COMMAND=`echo $COMMAND | sed "s/ TR_NPROC/ $LOC_NPROC/"`
 	    if test "x$MPI_MFILE" != x ; then
-	      COMMAND=`echo $COMMAND | sed "s/ TR_MFILE / ..\/..\/$LOC_MFILE /"`
+	      COMMAND=`echo $COMMAND | sed "s/ TR_MFILE / ..\/$LOC_MFILE /"`
 	    fi
 	    #echo "  COMMAND='$COMMAND'"
           fi
@@ -1404,15 +1411,17 @@ runmodel()
 	    rm -f $OUTPUTFILE $RUNLOG ; touch $RUNLOG
 	    if test -f run.log_tmp ; then cat run.log_tmp >> $RUNLOG ; fi
 	#- Divided Adjoint Run:
+	    add_DIVA_runs=0
 	#  get the number of additional runs (add_DIVA_runs) from file "run_ADM_DIVA"
 	    if test $KIND = 2 -a -f run_ADM_DIVA ; then
 	      adm_diva_nb=`sed -n '/^ *add_DIVA_runs *=/p' run_ADM_DIVA | sed 's/ //g'`
 	      echo " Divided Adjoint Run: $adm_diva_nb" >> $RUNLOG
 	      eval "let $adm_diva_nb"
 	      if [ $add_DIVA_runs -ge 1 ] ; then
+		extraRuns=`expr $add_DIVA_runs - 1`
 		rm -f costf* divided.ctrl snapshot*
 		echo -n "(add_DIVA_runs=$add_DIVA_runs) ... "
-		for ii in `seq 1 $add_DIVA_runs` ; do
+		for ii in `seq 0 $extraRuns` ; do
 		  ( eval $COMMAND ) >> $RUNLOG 2>&1
 		  echo " additional DIVA run # $ii : done" >> $RUNLOG
 		  mv -f $OUTPUTFILE ${OUTPUTFILE}.diva_${ii}
@@ -1634,7 +1643,6 @@ scandirs()
     fi
 }
 
-
 check_eedata()
 {
     # check_eedata eedata size.h
@@ -1676,7 +1684,6 @@ check_eedata()
 }
 
 ###############################################################################
-
 
 #  Default properties
 debug=0
@@ -1731,10 +1738,12 @@ EXTRFLG=
 NOCATAD=
 MKSMALLF=
 OADSINGULARITY=
+CHECK_PASS=f
 
 #- type of testing (KIND):
-#   KIND=0 : forward (= default) ;  KIND=1 : Tangent Linear with TAF ;
-#   KIND=2 : Adjoint with TAF ;     KIND=4 : Adjoint with OpenAD
+#   KIND=0 : forward (= default) ;     KIND=6 : Adjoint with OpenAD
+#   KIND=1 : Tangent-Linear with TAF ; KIND=2 : Adjoint with TAF ;
+#   KIND=4 : Tang-Lin. with Tapenade ; KIND=5 : Adjoint with Tapenade ;
 KIND=0
 
 # list of pTracers to check for monitor output
@@ -1829,6 +1838,8 @@ for ac_option ; do
 	-postclean | --postclean | -pc | --pc) POSTCLEAN=2 ;;
 	-deloutp | --deloutp | -do | --do) POSTCLEAN=1 ;;
 
+	-pass) CHECK_PASS=t ;;
+
 	-mpi | --mpi) MPI=2 ;;
 	-MPI | --MPI) ac_prev=MPI ;;
 	-MPI=* | --MPI=*) MPI=$ac_optarg ;;
@@ -1841,14 +1852,17 @@ for ac_option ; do
 
 	-mth) MULTI_THREAD=t ;;
 
-	-tlm) if test $KIND = 0 ; then KIND=1 ; else
-		echo "Error: '-tlm', '-adm' and '-oad' are exclusive" ; usage
+	-tlm) if test $KIND = 0 -o $KIND = 3 ; then KIND=`expr $KIND + 1`; else
+		echo "Error: '-tlm', '-adm' and '-oad' are exclusive + no duplicate" ; usage
 	      fi ;;
-	-adm | -ad) if test $KIND = 0 ; then KIND=2 ; else
-		echo "Error: '-tlm', '-adm' and '-oad' are exclusive" ; usage
+	-adm | -ad) if test $KIND = 0 -o $KIND = 3 ; then KIND=`expr $KIND + 2` ; else
+		echo "Error: '-tlm', '-adm' and '-oad' are exclusive + no duplicate" ; usage
 	      fi ;;
-	-oad) if test $KIND = 0 ; then KIND=4 ; NODEPEND=t ; else
-		echo "Error: '-tlm', '-adm' and '-oad' are exclusive" ; usage
+	-tap) if [ $KIND -le 2 ] ; then KIND=`expr $KIND + 3` ; else
+		echo "Error: '-tap' and '-oad' are exclusive + no duplicate" ; usage
+	      fi ;;
+	-oad) if test $KIND = 0 ; then KIND=6 ; NODEPEND=t ; else
+		echo "Error: '-tlm', '-adm' and '-oad' are exclusive + no duplicate" ; usage
 	      fi ;;
 	-oadsingularity | --oadsingularity | -oadsngl | --oadsngl) ac_prev=OADSINGULARITY ;;
 	-oadsingularity=* | --oadsingularity=* | -oadsngl=* | --oadsngl=*) OADSINGULARITY=$ac_optarg ;;
@@ -1909,7 +1923,7 @@ if test "x$MPI" != x0 -a "x$MPI_MFILE" != x ; then
     fi
 fi
 
-#- setting for forward or ADM testing
+#- setting for forward, TLM or ADM testing
 if test $KIND = 1 ; then
     if test "x$TARG" = x        ; then TARG=ftlall ; fi
     if test "x$TARG" = xobj     ; then TARG=ftlobj ; fi
@@ -1926,7 +1940,13 @@ elif test $KIND = 2 ; then
     inputdir=input_ad
     ref_outp="output_adm.txt"
     EXECUTABLE="mitgcmuv_ad"
-elif test $KIND = 4 ; then
+elif test $KIND = 4 -o $KIND = 5 ; then
+    if test $KIND = 4 ; then TARG=tap_tlm ; else TARG=tap_adj ; fi
+    code_dir=code_tap
+    inputdir=input_tap
+    ref_outp="output_${TARG}.txt"
+    EXECUTABLE="mitgcmuv_${TARG}"
+elif test $KIND = 6 ; then
     TARG=adAll
     code_dir=code_oad
     inputdir=input_oad
@@ -1939,6 +1959,19 @@ else
     EXECUTABLE="mitgcmuv"
 fi
 if test "x$JOBS" != x ; then TARG="-j $JOBS $TARG" ; fi
+
+if [ $verbose -gt 1 ]; then
+    echo ""
+    echo "--- print $0 setting:"
+    echo " KIND     =  '$KIND'"
+    echo " TARG     =  '$TARG'"
+    echo " code_dir =  '$code_dir'"
+    echo " inputdir =  '$inputdir'"
+    echo " ref_outp =  '$ref_outp'"
+    echo " EXECUTABLE= '$EXECUTABLE'"
+    echo "--- printing ends."
+   #exit 0
+fi
 
 xx=`echo $TESTDIRS | awk '{print $1}'`
 if test "x$TESTDIRS" = x ; then
@@ -1985,7 +2018,7 @@ done
 if test $count = 1 ; then echo "" ; echo -n " ... " ; fi
 #echo 'TESTDIRS='${TESTDIRS}'<'
 
-LOC_MFILE='tr_mpi_mfile'
+LOC_MFILE='mpi_mfile.loc'
 RUNLOG="run.tr_log"
 if test -n "$SBATCH" ; then
   OUTPUTFILE="STDOUT.0000"
@@ -2130,18 +2163,18 @@ if test $KIND = 0 ; then
     done
 else
   if test $KIND = 1 ; then
-   #echo "TANGLIN=true" >> $SUMMARY
     echo "TangLin generated by TAF" >> $SUMMARY
-  elif test $KIND = 3 ; then
-    echo "TangLin generated by OpenAD" >> $SUMMARY
   elif test $KIND = 2 ; then
-   #echo "ADJOINT=true" >> $SUMMARY
     echo "Adjoint generated by TAF" >> $SUMMARY
+  elif test $KIND = 4 ; then
+    echo "TangLin generated by Tapenade" >> $SUMMARY
+  elif test $KIND = 5 ; then
+    echo "Adjoint generated by Tapenade" >> $SUMMARY
   else
     echo "Adjoint generated by OpenAD" >> $SUMMARY
   fi
     line_0=`printf '%s %2i' 'default   ' $MATCH_CRIT`
-  if test $KIND = 1 -o $KIND = 3 ; then
+  if test $KIND = 1 -o $KIND = 4 ; then
     line_1="G D M    C  T  F"
     line_2="e p a R  o  L  D"
   else
@@ -2169,6 +2202,8 @@ if test "x$CLEANUP" != xt ; then
     echo ""        | tee -a $SUMMARY
 fi
 echo "-------------------------------------------------------------------------------"
+
+allpass=t
 
 conselems=" C  N  P Fe Si  A  O"
 testoutput_cons() {
@@ -2255,7 +2290,9 @@ for dir in $TESTDIRS ; do
         continue
     fi
 
-    if test "x$MPI" != "x0" ; then
+    if test "x$MPI" = "x0" ; then
+	LOC_NPROC=1
+    else
         ntx=1 ; nty=1
         if test "x$MULTI_THREAD" = "xt" ; then
           ff=$dir"/input/eedata.mth"
@@ -2280,17 +2317,17 @@ for dir in $TESTDIRS ; do
         )
         if test "x$MPI_MFILE" != x ; then
             #- create new MPI machine-file with the right number of Procs
-            rm -f $LOC_MFILE
-            cat $MPI_MFILE | sort | uniq | head -$LOC_NPROC > $LOC_MFILE
-            nl=`wc -l $LOC_MFILE | awk '{print $1}'`
+            rm -f $dir/$LOC_MFILE
+            cat $MPI_MFILE | sort | uniq | head -$LOC_NPROC > $dir/$LOC_MFILE
+            nl=`wc -l $dir/$LOC_MFILE | awk '{print $1}'`
             if [ $nl -lt $LOC_NPROC ] ; then
-                rm -f $LOC_MFILE
-                cat $MPI_MFILE | head -$LOC_NPROC > $LOC_MFILE
-                #sed -n "1,$LOC_NPROC p" $MPI_MFILE > $LOC_MFILE
+                rm -f $dir/$LOC_MFILE
+                cat $MPI_MFILE | head -$LOC_NPROC > $dir/$LOC_MFILE
+                #sed -n "1,$LOC_NPROC p" $MPI_MFILE > $dir/$LOC_MFILE
             fi
             if [ $verbose -gt 1 ]; then
                 nl=`wc -l $LOC_MFILE | awk '{print $1}'`
-                echo " new LOC_MFILE=$LOC_MFILE : $nl procs for LOC_NPROC=$LOC_NPROC"
+                echo " new LOC_MFILE=$dir/$LOC_MFILE : $nl procs for LOC_NPROC=$LOC_NPROC"
             fi
         fi
         if test "x$MULTI_THREAD" = "xt" ; then
@@ -2386,6 +2423,9 @@ for dir in $TESTDIRS ; do
     fres=`formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} ${run:-N} $results`
     echo "$fres" | sed 's/ 99/ --/g' | sed 's/  > />/' | sed 's/  < /</' >> $SUMREST
     echo "fresults='$fres'" | sed 's/ 99/ --/g' >> $locDIR"/summary.txt"
+        if [[ ! "$fres" =~ " pass " ]]; then
+            allpass=f
+        fi
 
     if test -n "$diagres"; then
         echo "$diagres" >> $SUMDIAG
@@ -2432,6 +2472,9 @@ for dir in $TESTDIRS ; do
         echo "cons$rescons  $dir.$ex" >> $SUMCONS
 
         echo "fresults='$fres'" | sed 's/ 99/ --/g' >> $locDIR"/summary.txt"
+            if [[ ! "$fres" =~ " pass " ]]; then
+                allpass=f
+            fi
         if test "x$POSTCLEAN" = x2 ; then
             run_clean $dir/$pfxdir.$ex
         fi
@@ -2476,6 +2519,29 @@ for dir in $TESTDIRS ; do
                   rm -f tmp.tr_log
                 fi
                 grep ' set FC_CHECK=' $gmkLog	>> $DRESULTS/genmake_state
+	    fi
+	    if test $KIND = 1 -o  $KIND = 2 ; then
+	      gmkLog=$dir/$builddir/taf_ad.log
+	      if test $KIND = 1 ; then gmkLog=$dir/$builddir/taf_ftl.log ; fi
+	      if test -f $gmkLog ; then
+		echo -n "from '$gmkLog', get: " >> $DRESULTS/genmake_state
+		head -1 $gmkLog | sed 's/^.*Algorithms in Fortran //' \
+						>> $DRESULTS/genmake_state
+		ADvers=`head -1 $gmkLog | awk '{print $7,$8}'`
+		sed "s/ by TAF/ by TAF $ADvers/" $SUMMARY > tmp.tr_log
+		mv -f tmp.tr_log $SUMMARY
+	      fi
+	    fi
+	    if test $KIND = 4 -o  $KIND = 5 ; then
+	      gmkLog=$dir/$builddir/make.tr_log
+	      if test -f $gmkLog ; then
+		ADtool=`grep '^Tapenade ' $gmkLog | tail -n 1`
+		echo "from '$gmkLog', get: $ADtool" >> $DRESULTS/genmake_state
+		#ADvers=`echo $ADtool | awk '{print $2,$3}'`
+		ADvers=`echo $ADtool | sed -e 's/^Tapenade //' -e 's/ [0-9]*:[0-9][0-9] .*$//'`
+		sed "s/ by Tapenade/ by Tapenade $ADvers/" $SUMMARY > tmp.tr_log
+		mv -f tmp.tr_log $SUMMARY
+	      fi
             fi
             gmkLog=$dir/$builddir/genmake_state
             if test -r $gmkLog ; then
@@ -2492,7 +2558,7 @@ for dir in $TESTDIRS ; do
         makeclean $dir/$builddir \
             && run_clean $dir/$rundir
     fi
-    if test "x$MPI" != x0 -a "x$MPI_MFILE" != x ; then rm -f $LOC_MFILE ; fi
+    if test "x$MPI" != x0 -a "x$MPI_MFILE" != x ; then rm -f $dir/$LOC_MFILE ; fi
 
     echo "-------------------------------------------------------------------------------"
 
@@ -2527,14 +2593,14 @@ if test "x$ADDRESSES" = xNONE -o "x$ADDRESSES" = x ; then
     echo "No results email was sent."
 else
     if test "x$SENDCMD" != x ; then
-	SendOpt='' ; headCMD=`echo $SENDCMD | awk '{print $1}'`
-	if test $headCMD != 'scp' ; then SendOpt='-s MITgcm-test -m 3555000' ; fi
+	sendOpt='' ; nb=`echo $SENDCMD | grep -c '\<scp\>'`
+	if [ $nb -eq 0 ] ; then sendOpt='-s MITgcm-test -m 3555000' ; fi
 	if [ $verbose -gt 1 ]; then
-	   echo " run: $SENDCMD $SendOpt ${SAVDIR}/${DRESULTS}".tar.gz" $ADDRESSES"
+	   echo " run: $SENDCMD $sendOpt ${SAVDIR}/${DRESULTS}".tar.gz" $ADDRESSES"
 	fi
 	tar -cf ${SAVDIR}/${DRESULTS}".tar" $DRESULTS > /dev/null 2>&1 \
 	    && gzip ${SAVDIR}/${DRESULTS}".tar" \
-	    && $SENDCMD $SendOpt ${SAVDIR}/${DRESULTS}".tar.gz" $ADDRESSES
+	    && $SENDCMD $sendOpt ${SAVDIR}/${DRESULTS}".tar.gz" $ADDRESSES
 	RETVAL=$?
 	if test "x$RETVAL" != x0 ; then
 	    echo
@@ -2568,4 +2634,9 @@ fi
 if test "x$DELDIR" = xt ; then
     rm -rf $DRESULTS
 fi
+
+if test "$CHECK_PASS" = t && test "$allpass" = f; then
+    exit 1
+fi
+
 echo "======== End of testreport execution ========"
